image: node:8.1

pipelines:
  branches:
    master:
      - step:
          script:
            - git config --global push.default simple && git remote add server ${SERVER_REPO} && git push server master --quiet
